"""The agent-facing schema card.

Written for a model's context window, not for humans: keep it token-efficient.
The query rules here are the agent's only defence against the traps documented
in CLAUDE.md, so they must stay in sync with `backend.domain.canonical`.
"""
from ..core.config import SCHEMA_CARD_PATH


def write_schema_card(tables: dict, tbb_footnotes: list) -> None:
    """Compact, token-efficient description of the lakehouse for the agent's context."""
    lines = [
        "# Lakehouse schema card",
        "",
        "TEMPORAL SEMANTICS ARE PER SERIES. Never difference a value before reading the",
        "temporal_semantics column (bulletin_observations, bulletin_metrics, macro_series).",
        "  stock          period-end level. Most BDDK tables. A month-over-month change is a",
        "                 NET balance change (new lending minus repayments, plus FX",
        "                 revaluation / write-offs), never 'new lending'.",
        "  cumulative_ytd BDDK dataset 'kar_zarar' ONLY: cumulated since 1 January, resets",
        "                 every January. Use value_flow for the month's own figure; `value`",
        "                 answers 'this year so far'. Differencing `value` across January",
        "                 gives a large negative number that means nothing.",
        "  ratio          a published ratio ('rasyolar', 'yurt_disi_sube_rasyolari'); not",
        "                 additive and not comparable across rows with different units.",
        "UNITS ARE PER ROW, NOT PER SOURCE. bulletin_observations.unit is authoritative;",
        "it is read from each response's own caption, never assumed.",
        "  milyon TL  fourteen of the seventeen bulletin tables (bilanco, krediler,",
        "             tuketici_kredileri, mevduat_*, sermaye_yeterliligi, ...).",
        "  bin TL     dataset 'sektorel_kredi_dagilimi' ONLY -- and the `observations`",
        "             table, which reads the same source and spells the unit identically.",
        "             So a figure from bulletin_observations is 1000x smaller than the same",
        "             figure from observations: NEVER compare or sum the two without rescaling.",
        "  %, adet, gün, kişi   rasyolar mixes all four; kobi_kredileri mixes milyon TL",
        "             with adet (customer counts); diger_bilgiler is adet throughout.",
        "Always SELECT unit alongside value, and state the unit in any answer.",
        "BDDK and TBB_RM are methodologically different sources: compare, never merge.",
        "BDDK 'follow-up' and TBB 'liquidation' are DIFFERENT concepts (persistent ~19-21% gap,",
        "documented scope differences; see reconciliation_monitor before explaining it).",
        "",
        "## Tables",
    ]
    for name, frame in tables.items():
        periods = ""
        if "period" in frame.columns:
            periods = f", periods {frame.period.min()}..{frame.period.max()}"
        lines.append(f"- **{name}** ({len(frame):,} rows{periods}): {', '.join(frame.columns)}")
    lines += [
        "",
        "## Query rules",
        "- bulletin_metrics lists every (dataset, metric, currency, unit) with its",
        "  temporal_semantics and metric_kind. metric_kind='size_bucket' / 'maturity_bucket'",
        "  means the metric column names a BRACKET, not a measure: dataset 'mevduat_turler'",
        "  splits deposits by size (on_bin .. milyonarti), 'mevduat_vade' and",
        "  'likidite_durumu' by maturity. metric='toplam' there is the total ACROSS buckets,",
        "  not a currency total; currency IS NULL for those tables because they publish none.",
        "- currency='total' means TL+FX. Filter to it unless the question is about the",
        "  currency split, otherwise summing TL, FX and total triple-counts.",
        "- Row identities are parsed from the labels themselves ('Tüketici Kredileri (2+3+4)')",
        "  and verified every build; the `formula` column carries the rule for that period.",
        "- bulletin_footnotes holds BDDK's own methodology note per dataset and period span.",
        "  READ IT BEFORE SUMMING ROWS. Three notes change what a sum means:",
        "  * 'sektorel_kredi_dagilimi': 'Bankalara Kullandırılan Krediler' is informational",
        "    and is NOT in the table's totals -- adding it double-counts nothing but inflates.",
        "  * 'menkul_kiymetler' / 'bilanco_disi_islemler': repo-subject securities and",
        "    collateral letters of guarantee are likewise outside their totals.",
        "  * 'kobi_kredileri': one customer using several loan types is counted ONCE in the",
        "    total column, so customer counts are NOT additive across rows.",
        "  A row carrying a '*' in bulletin_observations.footnote is explained there.",
        "",
        "## BDDK weekly bulletin (weekly_observations, weekly_items)",
        "- A SEPARATE release from the monthly bulletin, not a finer grain of it: 9 tables,",
        "  201 items, observed on FRIDAYS (the last business day when Friday is a holiday).",
        "  period is that observation date, never a month. All of it is milyon TL and stock.",
        "- Use it for timeliness (it leads the monthly bulletin by weeks) and for intra-month",
        "  movement. For a month-end level prefer bulletin_observations: the weekly figure is",
        "  a flash estimate the monthly one revises. Measured on the 10 dates where a week",
        "  lands on a month end, the two agree to within 0.19% -- see data_quality_report",
        "  rows 'weekly vs monthly ...'. Only 10 of 296 weeks land on a month end, so NEVER",
        "  compare a weekly row to a monthly row on any other date.",
        "- currency uses the SAME vocabulary as bulletin_observations: 'TL', 'FX', 'total'.",
        "  total is TL+FX; summing all three triple counts.",
        "- weekly_items.is_informational=TRUE means the label says '(Bilgi)' / '(Bilgi için)':",
        "  the row is published for information and is OUTSIDE its table's totals. 31 of the",
        "  201 items. Adding them to a total inflates it. The monthly bulletin hides the same",
        "  fact in bulletin_footnotes; here it is a column.",
        "- weekly_items.retired_on IS NOT NULL means BDDK replaced that item's DEFINITION on",
        "  that date. The replacement carries the same numbers over the overlap (proved every",
        "  build; see weekly_lifecycle_report check='superseded_series'), so retired and",
        "  current rows DUPLICATE each other before the retirement date. Filter",
        "  retired_on IS NULL for any aggregate or time series; read retired rows only to see",
        "  the superseded classification.",
        "- entity_key is BDDK's own item id, not the label: table 297 replaced ten items with",
        "  ten whose labels are identical, so labels do not identify a series. Join",
        "  weekly_items on entity_key for the label, parent, formula and flags.",
        "- Sector hierarchy: BDDK parents already contain their children; sum only rows",
        "  with relation='top_level' for national aggregates, or use the TOPLAM/TOTAL row.",
        "  BDDK sector 46 is a non-additive detail of 45. TBB sub-sectors sit under parent_code.",
        "- Cross-source questions: read reconciliation_monitor (bddk_value, tbb_value,",
        "  divergence_pct, out_of_band). If out_of_band=True, report a divergence regime",
        "  change instead of the standard methodology explanation.",
        "",
        "## TCMB EVDS macro series (source='TCMB_EVDS')",
        "- macro_series is the index: search name_tr/name_en, then query macro_observations",
        "  by series_code. Every series carries temporal_semantics (stock/flow/rate/index),",
        "  unit, native_frequency and monthly_rule (how sub-monthly data became monthly).",
        "- macro_series.unit is PER SERIES and normalised; TCMB's own string is per DATA GROUP",
        "  and kept unchanged in unit_source. Filter and report on `unit`, never unit_source:",
        "  one group publishes 'milyon TL ve yüzde' over eleven TL amounts plus a percentage",
        "  (TP.APIFON4 is the % one), and 92 interest-rate series say 'Ağırlıklı ortalama',",
        "  which is a method, not a unit. Vocabulary: %, endeks, adet, bin/milyon/milyar TL,",
        "  TL, milyon/milyar ABD doları, bin kişi, m2, TL/kg, TL/gr, USD/ons, Euro/ons.",
        "- macro_observations is MONTHLY (period = first day of month). value follows",
        "  monthly_rule; value_avg and value_last are always there (use value_last for",
        "  month-end FX rates and balances, value_avg for interest rates).",
        "- Quarterly series (GDP, bank lending survey) appear only on Mar/Jun/Sep/Dec rows.",
        "- macro_observations_native keeps the daily/weekly points for high-frequency work.",
        "- Demo keys: TP.KTF12 housing loan rate (%, weekly avg); TP.GENENDEKS.T1 TÜFE 2003=100;",
        "  TP.KFE.TR house price index; TP.AKONUTSAT1.KTRTOPLAM / TP.AKONUTSAT2.KTRTOPLAM total /",
        "  mortgaged house sales (count, monthly flow); DERIVED.IPOTEKLI_PAY.KTRTOPLAM their ratio (%);",
        "  TP.APIFON4 TCMB average funding cost = policy-rate proxy. Province-level sales use the",
        "  same codes with the province suffix (see name_tr). Housing loan STOCKS are in",
        "  bulletin_observations (dataset='tuketici_kredileri', entity_key='tuketici_kredileri_konut').",
        "- Real terms: divide a TL amount by TP.GENENDEKS.T1 and rescale; index 2021-01=100 by",
        "  dividing by the 2021-01 value. Do both in SQL, never in prose.",
        "",
        "## TBB methodology footnotes (primary source, June 2026 report)",
    ]
    lines += [f"> {note}" for note in tbb_footnotes]
    SCHEMA_CARD_PATH.write_text("\n".join(lines), encoding="utf-8")
